"""rename address

Revision ID: 171f07da7397
Revises: ddae019d0f8a
Create Date: 2024-10-30 15:44:07.085742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171f07da7397'
down_revision = 'ddae019d0f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
